### ISSUE TITLE
Issues with the mod

### ISSUE THREAD

**Issue by SerenModz21** [ReplayMod/ReplayMod#102]
I noticed the text is all messed up on my screen
![image](https://user-images.githubusercontent.com/41450647/73618823-26158b80-4622-11ea-8af8-b5f1804fe1ea.png)
also when i tried to register, i kept getting a error but it cant be an issue with my internet as my internet is working fine hence why im able to make this issue
![image](https://user-images.githubusercontent.com/41450647/73618855-552bfd00-4622-11ea-8d18-1e8ab82f81ce.png)

Here is a list of my mods versions:
![image](https://user-images.githubusercontent.com/41450647/73618879-6aa12700-4622-11ea-93f9-bca19c580f13.png)

**Comment by Johni0702** [comment]
For the messed up text, that's probably because of an incompatibility with newer fabric-api versions. You could try one of the 0.3.x versions and if that fixes it, please report back in #101.

As for the connection error when registering, looks like this broke when I upgraded some of the server software and we didn't notice because we don't usually test registration. Will get back to you on that one once I figure out the best way to fix it.
