### ISSUE TITLE
Error when using Biome Bundle

### ISSUE THREAD

**Issue by SouthernPixel** [ReplayMod/ReplayMod#110]
I Have everything for Biome Bundle and all my other mods are working fine except for when i leave a game and try to save the replay.

https://pastebin.com/YujDnTGe

**Comment by Johni0702** [comment]
Known issue with certain third-party mods (in this particular case OTG): #69
See the last paragraph of my first reply over there for a workaround.

**Comment by SouthernPixel** [comment]
Im confused though, if I cant use stop/start then that means i cant even edit the replay at all

**Comment by Johni0702** [comment]
Are you maybe confusing the Play/Pause button (hotkey P) in the replay editor with the Start/Stop/Pause/Resume buttons in the menu during recording? The latter is broken, the former should be working fine.

Replays which use BoP, OTG or similar can not currently be cut because the thing which was formerly caller Replay Editor doesn't current work with them (and the Start/Stop/Pause/Resume feature uses the Replay Editor in the background), it's all or nothing.
