### ISSUE TITLE
Unable to compile 1.15.2

### ISSUE THREAD

**Issue by yoerithor** [ReplayMod/ReplayMod#127]
Hi, to start. Thank you very very much maintaining ReplayMod <3

Scan report: https://gradle.com/s/bpmoizh5gvuym
Command: `./gradlew :1.15.2:build --scan`
commit: 39ccf60

Believe this is all the info you need... Please let me know if you need more :D
Thanks :)

**Comment by Johni0702** [comment]
Looks like the `jGui` submodule is missing. Make sure to either clone with `--recursive` or run `git submodule update --init --recursive` after cloning.

**Comment by yoerithor** [comment]
Fixed that problem. Thank you very much! But,,,
now got this: https://gradle.com/s/irp4tgwkra7k2

Thx for responding btw :D

**Comment by Johni0702** [comment]
That scan isn't currently accessible.

**Comment by yoerithor** [comment]
No? Weird

Is there another way to report the error? Just I just paste the entire console log to pastebin or something?

**Comment by Johni0702** [comment]
Working now. Looks like you're running into https://github.com/rzwitserloot/lombok/issues/1651
So you'll either need to use an older java version or update lombok in `versions/common.gradle` and `jGui/versions/common.gradle`.
Please keep this issue open either way as a reminder for me to do the latter when I next work on it.

**Comment by yoerithor** [comment]
Got a lot further, but still spitting out errors :/
scan report: https://scans.gradle.com/s/fydsjujuhq4jg

**Comment by Johni0702** [comment]
Eh, tests are probably just legitimately broken. We don't have many so I haven't bothered running them any time recently. Try building with just `./gradlew :1.15.2:shadowJar` (in fact, that should already have been executed, you should already be able to find the jar files in `versions/1.15.2/build/libs/`).

**Comment by yoerithor** [comment]
Yay, got it working with disabling the testing with `-x test`

Thank you very much for the support. Lovu

**Comment by yoerithor** [comment]
Ohh gosh thank you so freaking much. Optifine shaders are working now perfectly, everything is smooth :D

You're a god, honestly :p

**Comment by Xanton19** [comment]
FYI I have also run into this issue with `./gradlew :1.15.2:build` a while ago and was wondering what that test HTML meant until @Johni0702 told me to compile 1.15 with `./gradlew :1.15.2:shadowJar` in my previous #116 thread.

Maybe updating the README.md file to the new commands (`./gradlew :1.15.2:shadowJar`) for compiling the new version might help new users out to compile the updated `develop` branch without a build failed, unless the `./gradlew :1.15.2:build` command is fixed with the tests.

**Comment by Johni0702** [comment]
@Xanton19 `./gradlew :1.15.2:build` is supposed to work. I just tend to use `./gradlew :1.15.2:shadowJar` myself because it's quicker (as it doesn't run the tests), so I haven't yet bothered to fix the tests (idk why they're failing on 1.15.2 but whatever it is should probably be fixed).

**Comment by Xanton19** [comment]
Thank you for your fast reply. `./gradlew :1.15.2:shadowJar` works fine for me since the closure of the #116 thread, just wanted to inform about the `./gradlew :1.15.2:build` command with the reply. Anyways thank you very much for your amazing job, in developing a 1.15 version of the mod. I am really grateful for that and I wish you a happy easter :)
