### ISSUE TITLE
Feature Request - Being able to prevent replay mod on servers.

### ISSUE THREAD

**Issue by smartin1018** [ReplayMod/ReplayMod#14]
Hey, pretty much in the title. I was aware that you were adding this feature, so I decided to post and see if there's any news.

**Comment by Johni0702** [comment]
Replay Restrictions has been working since a804d6b (included in *-2.0.0-b3).

Have a look at [this](https://gist.github.com/Johni0702/2547c463e51f65f312cb) gist for a explanation of the protocol. To this date, none of the restrictions listed there are implemented.
To simply prevent all Replay Mod usage on a server, you can simply set a custom restriction which will cause the mod to refuse to play the replay.

We provide sample Bukkit, Sponge and BungeeCord plugins in [ReplayMod/replay-restrictions](https://github.com/ReplayMod/replay-restrictions). No built jar files are available, you'll have to build them yourself.
There is also [this] 3rd party plugin for CraftBukkit/Spigot which even works with the old ReplayMod 1.0.x versions.

**Comment by smartin1018** [comment]
Alright. Thanks
