### ISSUE TITLE
The mod doesn't show.

### ISSUE THREAD

**Issue by ImASquirrelYipee** [ReplayMod/ReplayMod#145]
No mod and no buttons.

**Comment by haykam821** [comment]
What do you mean?

**Comment by SeagalKru** [comment]
(Google translation from Russian)
Hello!
I have a similar situation: the mod is in the “mods” folder, but when loading the game it does not load: there are also no buttons in the menu and when loading, the OpenEye mod is not requested to load.
I enclose the client download log file.
[latest.log](https://github.com/ReplayMod/ReplayMod/files/4541695/latest.log)

**Comment by Johni0702** [comment]
This is caused by MalisisCore bundling an old Mixin version: https://github.com/Ordinastie/MalisisCore/issues/172

As a workaround, you can try to rename either the ReplayMod jar to start with `a` (`areplaymod-1.12.2-2.3.0-b1.jar`) or the MalisisCore jar to start with `z` (`zmalisiscore-1.12.2-6.5.1.jar`), either way the ReplayMod jar (and therefore its more up-to-date Mixin lib) should be loaded before MalisisCore.

**Comment by SeagalKru** [comment]
And is this information necessary to transmit to the developer of the Malisys Door mod or is this done automatically?

**Comment by Johni0702** [comment]
@SeagalKru The issue I linked to is the same thing except with VanillaFix instead of ReplayMod, so they should already be aware.

**Comment by SeagalKru** [comment]
Hmm ... Well, good. Then we will wait for the fixes! ;)
