### ISSUE TITLE
[1.14.4] Fabric crash on startup

### ISSUE THREAD

**Issue by Jessebeau2001** [ReplayMod/ReplayMod#149]
The Replay mod instantly crashes the game when you try to run it.

I have The latest version of Fabric API (0.5.12 build 249) and the Fabric loader (0.8.2 build 194) installed.

Game Logs:
[latest.log](https://github.com/ReplayMod/ReplayMod/files/4552545/latest.log)

**Comment by Hazmi35** [comment]
Same issue here

**Comment by Jessebeau2001** [comment]
I'm pretty sure this has something to do with fact that Mixin is now shipped from within the replay mod. It cant find/access a certian class which I believed to be a Replaymod Core  class but on further inspection that doesnt seem to be the case. I have almost no experience with Java or programming whatsoever so I could be totally wrong here but just wanted to leave my reply anyway.

**Comment by Johni0702** [comment]
@Jessebeau2001 No, it's because we internally build a non-functional 1.14.4 Forge version (because that way we can more easily map our 1.14.4 Fabric code to 1.12.2 Forge) and due to an oversight (same file name) that one got released instead of the 1.14.4 Fabric version.

I've already fixed that (but have not yet pushed it), so the next release should be the proper version again.
You can also get the real one from https://jenkins.johni0702.de/blue/organizations/jenkins/ReplayMod/detail/develop/6/artifacts/ (`versions/1.14.4-forge/build/libs/replaymod-1.14.4-2.3.0-b1.jar` is the one which was released but `versions/1.14.4/build/libs/replaymod-1.14.4-2.3.0-b1.jar` should have been).

**Comment by Hazmi35** [comment]
Ah I see

**Comment by Jessebeau2001** [comment]
Hey thanks for the great work guys
