### ISSUE TITLE
Replaymod 1.12.2 has problems with the following mods

### ISSUE THREAD

**Issue by ImEthanBradberry** [ReplayMod/ReplayMod#186]
Since Minecraft 1.12.2 has the best mods and a lot of people still use them, specially the following mods, I think it's important to fix it:

-Emoticons mod: 
https://www.curseforge.com/minecraft/mc-mods/emoticons

When trying to render a movie, for some reason when using this mod, Replaymod ignores when you uncheck the "Render Name Tags" box, so it just renders the nametag even if you don't want to.

-Seus Renewed 1.0.1 shaders
https://sonicether.com/shaders/download/renewed-v1-0-1/

The movie is rendered with visual glitches, the player movement is ghosted. Please see:
https://vimeo.com/421572858

It would be great if you can fix this because like I said before those mods are pretty basic when making machinimas, but you can't use them with Replaymod as it stands.

Im using replaymod-1.12.2-2.3.0.jar and this has been happening since I ever tried to do a movie with this program using Emoticons, when I realized I couldn't get rid of nametags if I used it.
The shaders I have been trying recently because I bought a new computer and back then I wasn't able to use them. My specs are:

CPU: 3950x
GPU: 1660 super
32GB ram
Windows 10 Enterprise 1809 LTSC

Thanks.

**Comment by ImEthanBradberry** [comment]
What happened to the replies?

**Comment by Johni0702** [comment]
> Emoticons mod
> When trying to render a movie, for some reason when using this mod, Replaymod ignores when you uncheck the "Render Name Tags" box, so it just renders the nametag even if you don't want to.

RM doesn't ignore the checkbox, nor does it render the nametags, it's MC which does that and RM just adds a check ([here](https://github.com/ReplayMod/ReplayMod/blob/57c7362e3417ec563235a3e41a300e4a2ab9a709/src/main/java/com/replaymod/render/mixin/MixinRender.java)) to prevent that when the box is ticked.
Emoticons seems to bypass that check for some reason. They do not provide any publicly visible source code for their mod, so that's about all I can tell you and it's on them to fix. See https://github.com/mchorse/emoticons/issues/13.

> Seus Renewed 1.0.1 shaders

Same applies here: Optifine's author does not provide any publicly visible source code for their mod, so I cannot help with issues related to it. You're at the mercy of its author.

> What happened to the replies?

Huh? Dunno. Maybe they deleted their account.
