### ISSUE TITLE
Unhelpful error message when FFmpeg startup fails

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#205]
[latest (33).log](https://github.com/ReplayMod/ReplayMod/files/4711099/latest.33.log)

Reported by LGK Ixarlo.
I have no clue how to help them, cause the error message isn't very descriptive.
Maybe add the log in question to the Exception's error message?

**Comment by Johni0702** [comment]
The log is already part of the exception and included in the crash report. The problem is that MC's `ReentrantThreadExecutor` doesn't have any special handling for ReportedExceptions.
We could probably add our own catch to handle them at https://github.com/ReplayMod/ReplayMod/blob/20b410f963349063df710d33d9e9bfd9265785c9/src/main/java/com/replaymod/core/ReplayMod.java#L541-L543

> I have no clue how to help them

Ask them for the `export.log` file.

**Comment by CrushedPixel** [comment]
They sad they don't have an `export.log`, but I'll ask again

**Comment by Johni0702** [comment]
Please do. Not having an `export.log` file is not an option, that throw happens after opening the file.

**Comment by CrushedPixel** [comment]
> are you sure you don't have an export.log?

> yes i'm sure

welp, can't help them, I guess
