### ISSUE TITLE
Replaymod records when it's not supposed to

### ISSUE THREAD

**Issue by supsm** [ReplayMod/ReplayMod#251]
I have `Automatic Recording` turned off in the replaymod settings, but replaymod still records for a small amount of time when i join hypixel (maybe when it's loading). Also, I've noticed that this one file (`.minecraft\replay_recordings\[random date].mcpr.tmp\changed\recording.tmcpr`) is quite large (1 GB or so), even though I only have recordings that are less than one second long (mentioned above).

**Comment by Johni0702** [comment]
The Start/Stop/Pause/Resume recording feature is a lie. The mod always records (unless you un-tick the Record Singleplayer/Multiplayer checkboxes) and only in post tries to squash the parts where it wasn't supposed to be recording.
It has to do that because there's no way for the client to create a snapshot of the current state, so we have to take the one which the server sends us on connect and also keep track of all changes since then.
This could have been done all in memory but that would result in significantly increased memory usage and more importantly no way to recover from a bug in the fairly complicated squashing code. Instead I've opted to just save the uncut recording as usual (but only for three weeks in the `.minecraft/replay_recordings/raw/` folder) and apply the squashing afterwards. That way, if there's a bug in the squashing code, it's a lot easier to debug and people can just use the uncut replay till it's fixed.

**Comment by supsm** [comment]
Okay, thanks! Perhaps there could be an option to automatically delete replays less than x seconds long?
