### ISSUE TITLE
Commands button doesn't work during camera path playback

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#269]
The bottom left button that unfolds/folds the 14 commands, doesn't work during a camera path playback (bottom play button). It works during a replay playback (top play button), though.

Replay Mod v2.4.0
Minecraft 1.16.1

**Comment by Johni0702** [comment]
This is actually kind of working as intended. We block every button except for the stop path button so we don't have to deal with the path changing while we play it.
Made a lot more sense before I added the hotkey thing because back then pretty much every button would mess with the path.
It wasn't easily possible way back but by now we could totally just clone the entire path for playback and not block the UI at all, that'd probably make the most sense.

**Comment by TheChocolateOre** [comment]
Yeah, all good. No need to prioritize this too much. I mostly reported this, because my commands got stuck open, during a playback, and couldn't close them without pausing first. Not a big deal.
