### ISSUE TITLE
Add queue for rendering multiple replays

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#349]
You can queue multiple camera paths in a single replay file, but you can't queue multiple replay files.

**Comment by Johni0702** [comment]
This seems useful but I can't really find a nice way to do it UI-wise.

<details>
<summary>The render queue has changed a bit in develop compared to the last release</summary>

When you click the render button for the first time, this opens:
![](https://i.johni0702.de/T6FzV.png)
If you click the "Add to Queue", it'll get added to the queue:
![](https://i.johni0702.de/IgPhf.png)
Clicking the render button when there's stuff in the queue will also open above screenshot.
To then add further tasks, you click the "Add current configuration":
![](https://i.johni0702.de/UKIVy.png)

The queue is now also persisted in the replay file.
</details>

I suppose the most intuitive way would be to add a button to the Replay Viewer which renders the queues of all selected replays (one would have to add multi-select but that shouldn't be too difficult).
But I don't really like taking up more space in the Replay Viewer, and I fear that new users might find that "Render" button very confusing (especially because some already have difficulties grasping the difference between a replay and a video).

**Comment by TheChocolateOre** [comment]
> But I don't really like taking up more space in the Replay Viewer, and I fear that new users might find that "Render" button very confusing

The Replay Viewer could stay as it is, with the exception of the addition of 1 button (probably small) to move to a similar screen with more options.
