### ISSUE TITLE
Replay is absent immediately after exiting world and then entering the replay viewer

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#379]
Use case, that is easy to recreate:
1. Record a not short replay(3+mins is sufficient).
2. Exit world and immediately open the replay viewer.
3. The latest replay that was just recorded is missing.

You have to exit and re-open the replay viewer after waiting a few seconds to access the latest replay. Note that, if you won't exit the replay viewer and just wait, the replay will never appear, i.e. you have to re-enter in order for it to refresh.

Now, taking a step back, I don't think there is something wrong with the mechanism. Of course a not short replay needs a few more seconds to process, and as a result, opening the replay viewer before the replay is ready, it appears missing. Most users don't know about the technical stuff, on why it might be missing. From their perspective, their file is just missing and they might enter the previous replay, only to realise a few moments later that its not what they wanted. All that adds confusion and makes the software feel less reliable.

A few suggestions on how it can be improved:

1. A placeholder of the replay could be placed at its location, indicating that it is loading, blocking any access to it, until its done. When finished, the user can just enter the replay.
2. The user can enter the replay, even if its not ready yet, it will add up its processing time in the loading phase, when opening a replay.

Solution 1. seems attractive, but probably needs more work that 2. and the ability for the replay viewer ui to refresh (is that possible?).
Solution 2. might be better, cause the processing time is usually a few seconds. Adding a locked placeholder for that time is probably an overkill.

In every case the processing time can't be avoided. But, with the above solutions the user will never experience their replay file missing, just because they entered the replay viewer 1 second earlier.

**Comment by Johni0702** [comment]
RM 2.5 shows a "Saving Replay file" popup in the top right of the screen (regardless of which menu you're currently in) with a progress bar and when it's done with the option to rename or discard it (#319):
![](https://cdn.discordapp.com/attachments/709129817705938966/754277134503247892/Screen_Shot_2020-09-12_at_7.17.22_pm.png)
(ignore the checkbox, that's a bug, I didn't have a better screenshot at hand)

That should probably be enough for everyone to understand why it's not yet in the list.
It doesn't refresh the list though when you click Done while the list is already open, so that's probably still confusing and should really be implemented.
