### ISSUE TITLE
Replay Editor time markers should be placed at fixed pixel intervals, not time intervals

### ISSUE THREAD

**Issue by dbechrd** [ReplayMod/ReplayMod#429]
1) Editing a replay with a long duration (10+ hours or so) causes timeline labels to become a mess. This can be fixed by rendering fewer labels.

![image](https://user-images.githubusercontent.com/707367/100552405-ddc3fb80-323b-11eb-9c5e-59f8b9fc4f64.png)

2) Editing a replay seems to automatically insert an `_RM_SPLIT` and `_RM_START_CUT` marker automatically, neither of which can be deleted with the delete key (see screenshot above). I can sort of see this as trying to be helpful, but it's much more confusing than just starting with an empty set of markers IMO. If you want to give the user some default markers, I would suggest adding both `_RM_START_CUT` and `_RM_END_CUT` markers as a pair, and ensuring that any default split/cut markers are deletable just like additional markers added by the user to avoid having "special" default markers which look the same but can't be deleted.

3) It's confusing to the user that, when the Edit modal is open, all of the buttons on the Replay Viewer screen can be hover highlighted and display their tooltips, indicating that they could be clicked, but don't actually do anything when you click them. The modal should either visibly cover those other controls, or gray them out and disable hover highlight/tooltips to indicate that the modal is currently taking input precedence.

![image](https://user-images.githubusercontent.com/707367/100552619-3c3da980-323d-11eb-969f-00c4d63333a0.png)

**Comment by RaderRMT** [comment]
First point looks like a bug
Second point:
> Editing a replay seems to automatically insert an `_RM_SPLIT` and `_RM_START_CUT` marker automatically
That's the ReplayMod adding markers in the raw replay file when you use the start/stop/pause/resume feature.
I don't think you're supposed to be able to remove markers from the modal, use the Replay Viewer if you want to delete markers. (not in the menu but in game, with the timelines) <https://www.replaymod.com/docs/#replaying-markers>
Third point looks like a bug too

**Comment by Johni0702** [comment]
I'm splitting 3 off into #430 because it applies to all popups (and I only want to have one bug per issue, so they can be dealt with independently).

For 2, as Rader said, the "default" are from what you pressed during recording. Usually those are supposed to be applied automatically when you exit to the main menu but if you disable that or you directly close the game (or you don't wait long enough in the main menu, which seams plausible with huge replays), they won't be applied. They should definitely be removable though because they are no different than those which you add manually. If they really cannot be removed, please open a separate issue for that.

Keeping this issue open for 1.

**Comment by dbechrd** [comment]
> I don't think you're supposed to be able to remove markers from the modal, use the Replay Viewer if you want to delete markers. (not in the menu but in game, with the timelines) https://www.replaymod.com/docs/#replaying-markers

It would make no sense to be able to insert markers but not remove them. That would make the whole modal rather useless. You're definitely supposed to be able to remove markers (in fact, there should be buttons for this in addition to the not-so-obvious Delete hotkey).
