### ISSUE TITLE
Render chat and other ingame texts on screen

### ISSUE THREAD

**Issue by Wilker-a** [ReplayMod/ReplayMod#435]
hi!

i'm just here for now to ask a question, as i can't seem to be able to access the [documentation page](https://www.replaymod.com/docs/), even after disabling NoScript for the site.

i am trying to figure out right now how can i render the replay video, except with all of its recorded ingame elements such as the chat, inventory UIs and the big title texts which appears on the middle of the screen, but i can't seem to find any options available for it.

up to which extent can i do such things as of today? if already possible, how do i find this option?

thank you for the help <3 and also for making this mod :3

**Comment by RaderRMT** [comment]
For the UI, it's not being recorded by the replaymod, and will not be recorded by the ReplayMod in future versions:
> regardless of whether "it's worth it", from my point of view this is more an issue with feasibility:
the only reason the ReplayMod as a concept is feasible, is because there already exist a generic way to serialize (i.e. convert to/from a consistent binary fromat) the entire world state in Minecraft because that's fundamentally required for multiplayer to work (and singleplayer is just running an integrated server these days). all the world state has to somehow be replicated over the network and we can just take that replication data and store it for later (in actuality there's lots of complicating factors but vastly simplified that's how it works).
there's no such thing for GUIs. MC has no need to sync the exact state of one client's user interface to any other client. as such there's no generic way to record and later replay that state. and without a generic way to do that, it's basically a pick two out of three:
> - compact storage and flexible replay (i.e. not just a generic screen recorder)
> - possible to implement and maintain within reasonable effort
> - supports all the GUIs (including with third-party mods)

As for the chat and titles, ReplayMod basically render in F1 (with the exception of the arm with spectator keyframes) so they will not be visible
And for UIs, it's pretty much impossible.

**Comment by Wilker-a** [comment]
i see.

but because the chat is still recorded, can i at least render it with recorded ingame texts somehow?

**Comment by RaderRMT** [comment]
Nope

**Comment by Wilker-a** [comment]
i see :( thank you
