### ISSUE TITLE
RenderArrow crashes

### ISSUE THREAD

**Issue by NightW0lf93** [ReplayMod/ReplayMod#50]
There seems to be an issue between ReplayMod and some mods.
I say this because the game works fine when I disable Replay

[DE](https://github.com/ReplayMod/ReplayMod/files/2818283/crash-2019-01-31_10.51.24-client.txt)
[COFH Core](https://github.com/ReplayMod/ReplayMod/files/2818315/crash-2019-01-31_11.20.27-client.txt)
[TF](https://github.com/ReplayMod/ReplayMod/files/2818391/crash-2019-01-31_11.29.28-client.txt)
[Quark](https://github.com/ReplayMod/ReplayMod/files/2818414/crash-2019-01-31_11.44.26-client.txt)

They seem to be about RenderArrow (save for DE but I have a pretty good idea that it's still something about arrow rendering)

**Comment by Johni0702** [comment]
Considering the crashes all seem to be caused by an inability to load the RenderArrow class, I suspect that non of those mods are actually incompatible with the RM (I also know for a fact that TF used to load just fine with RM). They just happen to be the first ones to access that class after it got broken by something else.

The full log might contain more info which could help identify the real source of the issue.

**Comment by NightW0lf93** [comment]
[The full log](https://github.com/ReplayMod/ReplayMod/files/2818979/latest.log) as requested

**Comment by Johni0702** [comment]
Please give [this](https://minio.johni0702.de/replaymod/replaymod-1.12.2-2.1.4-5-g0ca8b41.jar) version a try.

**Comment by NightW0lf93** [comment]
It works!
Thank you!
