### ISSUE TITLE
1.13.2

### ISSUE THREAD

**Issue by ChineseMarc** [ReplayMod/ReplayMod#51]
As forge 1.13.2 is here you should update mod for 1.13.2
https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html

**Comment by Johni0702** [comment]
We're blocked waiting for [Mixin]. See [this](https://www.replaymod.com/forum/thread/2452#post10324) forum post for more info.

[Mixin]: https://github.com/SpongePowered/Mixin

Also, `should update` makes it sound like we're in some way obligated to update which we are not, just to make that clear.

**Comment by crazybytes** [comment]
Indeed.
I have program to create 1.12.2 region files.
If i use mc 1.12.2, there are like 45 degrees rotated columns from roof to bottom, that contains light.
Its a bug.
If i use mc 1.13.2, the glitch is gone, then the region files and lightning is ok. (Caves).
But i can not use replay mod.....

When i (tried everything, like edit world-> check box delete cache, update from 1.12.2 to 1.13.2, then from 1.13.2 to 1.14.3/4, also trough paper server with update chunks commands etc.) use 1.14.3/4, there is no block light, maybe because they use dynamic lightning. 

From the region file creating program i use torches, then the block light is calculated, then i delete the torches. If i don't, i see thousands of torches in the caves. (Whole region file is like closed cave).

So, in 1.12.2 i have the light glitch, its not ok for making movies.
In 1.13.2 i can not use the replay mod.
And in 1.14.x the block light is 0. So every thing is dark.
Now you can use 'hidden' glowstones etc. But for me its no option in the structures i am creating.
Also examined all light stuff mods.

You have any idea?

**Comment by Johni0702** [comment]
@crazybytes 
Pretty sure there are mods which add invisible light sources. I'd suggest asking in some general modding place (e.g. ftb subreddit), someone will probably be able to name you one such mod.
If there are no other torches or glowstone in your structure, then I think you could even use a resource pack to change one of their models to be invisible.
Also, if you just want everything illuminated, you can press Z in the replay viewer, though that might look bad if there are places which should be dark.
