### ISSUE TITLE
Client multipart @BlockPos{x=987, y=73, z=425} not found

### ISSUE THREAD

**Issue by feoranis26** [ReplayMod/ReplayMod#510]
When I view a replay the log file gets spammed with over 50,000 error messages. Then it kicks me out of the replay viewer with this error: `Client multipart @BlockPos{x=987, y=73, z=425} not found`. Even after I'm kicked out of the viewer it keeps spamming the log. Because of the large amount of errors in the log I can't find anything about the error I'm looking for. The error that's spammed is this:
```
[13:05:28] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13:05:43] [Client thread/ERROR]: Received invalid update packet for null tile entity at BlockPos{x=846, y=10, z=431} with data: {computerID:81,instanceID:39,fuelLevel:50873,leftUpgrade:"minecraft:diamond_pickaxe",rightUpgradeNBT:{active:1b},rightUpgrade:"computercraft:advanced_modem",animation:1,direction:3}
```

I can't attach the log file because it's over 10MB.

**Comment by RaderRMT** [comment]
upload the log to [https://linx.breizh.pm/](https://linx.breizh.pm/) and send the link once it's uploaded

**Comment by feoranis26** [comment]
https://linx.breizh.pm/55868jic.log

**Comment by RaderRMT** [comment]
1: update the replaymod. i don't know why you use such an old version, but please update it (you'll have to rename it so it's alphabetically before malisis).
2: Looks like "TheBetweenlands-3.7.3-SNAPSHOT-20210322.102210-core.jar" is causing a lot of errors. As for the `Received invalid update packet for null tile entity at [...]` errors, i don't know what can be causing them. you might have to wait for the dev to answer that question.

**Comment by feoranis26** [comment]
I'm using that version because anything newer causes a crash on startup.

**Comment by RaderRMT** [comment]
so you either cannot read an entire sentence, or you just want to read half of what i'm writing. I gave you the solution to the crash in the message where i asked you to update...

**Comment by feoranis26** [comment]
I updated the mod, https://github.com/ReplayMod/ReplayMod/issues/511 is the crash that happened after I updated.

**Comment by feoranis26** [comment]
I thought updating fixed this but I still have this issue.

**Comment by feoranis26** [comment]
Also the block at 987 73 425 is just stone and it didn't change in the recording.

**Comment by Johni0702** [comment]
> I thought updating fixed this as now I can view a bit of the replay but it looks like I still have this issue after a bit.

Please post an updated log file then.

**Comment by feoranis26** [comment]
It's the same error but here it is:
https://linx.breizh.pm/zeazw3sy.log

**Comment by Johni0702** [comment]
Please check if there is a replay file with the same timestamp in `.minecraft/replay_recordings/raw/`. If so try moving it up into the `replay_recordings` folder and test if it exhibits the same problem.
If it does, please post the corresponding log.
If it does not, then this is a (probably fundamental) incompatibility between the replay editor feature (used by the Start/Stop/Pause/Resume buttons) and one of your mods. In that case, refrain from using this feature with that mod.

**Comment by feoranis26** [comment]
That file works, but I don't think mod incompatibility is the problem, because I made around 3 timelapses with the same mods that I had while doing this timelapse.

Here is the log : https://linx.breizh.pm/1i9v1i1f.log

**Comment by Johni0702** [comment]
> I don't think mod incompatibility is the problem

I do. And seeing how I wrote the code and know how it works and what its limits are, I'm going to stick with that opinion until there's clear evidence to the contrary. Currently everything I've seen points at exactly towards one of the limits I'm thinking of. It's a fundamental issues with how Start/Stop/Pause/Resume works and an intentional compromise between compatibility and usefulness.
The issue probably could be fixed by changes in the respective third party mod but there isn't necessarily anything wrong with it as is (so I cannot fault its authors, nor expect them to fix it). It would just need to be able to deal more defensively with invalid packets (specifically with packets pointing at missing chunks).

> in another dimension [..] then I stoppped and started recording

So, using the replay editor feature (Start/Stop/Pause/Resume) while under heavy influence of another mod. Fits with what I would expect. If you did not do this in the previous timelapses, then I am not be surprised you did not have this issue with the previous timelapses.

To avoid it in the future, just don't use the Start/Stop/Pause/Resume buttons with this modpack (or maybe even just if you've been in that dimension, you can always use the raw replay if there is another condition which breaks it). Instead simply leave and re-join your world/server to split recordings.
