### ISSUE TITLE
Rendering extremely slow if the replay is playing when starting a render

### ISSUE THREAD

**Issue by DaCubeKing** [ReplayMod/ReplayMod#524]
Rendering becomes extremely slow if you don't pause the replay before starting a render. I think this is happening because the replay is still playing while the path is still being rendered. This then causes replay mod to have to continually jump back in time (which is very slow).

I think this could easily be fixed if pressing the export button would also just pause the replay.

**Steps to reproduce**
1. Play the replay with the second timeline (the one for the video export)
2. Try to render something without pausing the replay

**Comment by Johni0702** [comment]
I cannot reproduce this.
And unless I'm missing something, your suspicion cannot actually be correct because we run the replay sender in blocking mode (i.e. all packets must be fully processed before the next frame) during rendering whereas regular replay uses async mode (packets are read on a different thread and then sent to the main thread for processing an arbitrary amount of frames after they were requested). The two modes cannot be active at the same time and there are two separate methods to advance time which will throw an error if they are used while in the incorrect mode.

So there has to be something else going on and that isn't happening when I try it.

**Comment by DaCubeKing** [comment]
Oops, it looks like I didn't explain it well enough. (Also sorry for the late reply, I was on vacation).
You need to play the second timeline and then try to render something
Here is a video where I encounter this issue: https://www.youtube.com/watch?v=6QZx7mTcDp8 (0:20 for the normal render. 1:00 for the bugged render )
