### ISSUE TITLE
Using an ender pearl does not teleport the player to the correct location

### ISSUE THREAD

**Issue by DaCubeKing** [ReplayMod/ReplayMod#525]
Video of the glitch: https://youtu.be/KEYxJ48q3qI
Replay recording (Saved path shows the glitch): https://drive.google.com/file/d/13A6vuzYg1TINvCOGV3tiCN-A_EE-TwBI/view?usp=sharing
First Person View: https://youtu.be/pnCklQnxpaM

When the player teleports using an ender pearl the player doesn't get teleported properly to where the ender pearl landed. 

It looks like it might be an issue with recording. ie replay mod is not checking if the player is within the 4 block range that is allowed by the relative move packet. 
It also might be that because the server teleports the player it isn't saved in the replay for some reason?
Or I could have got it completely wrong and replay mod is not reading the packet properly.

I've only tested this on 1.8.9 if its a version-specific bug

**Comment by RaderRMT** [comment]
> Or I could have got it completely wrong and replay mod is not reading the packet properly.

there are no packets to tell where your player is, it's rotation, etc... RM has to hack in the recording player because the server does not echo back what the client sends (that would be pretty much useless):
> the recording player's movements are not echoed by the server, so we inject them on the client anyway.

([source](https://discord.com/channels/708304818829262910/708311773450731591/840624867309125652))
