### ISSUE TITLE
Crash when trying to cut or split a replay with a long name

### ISSUE THREAD

**Issue by Felix14-v2** [ReplayMod/ReplayMod#534]
[Demo](https://youtu.be/P68Wm4riLxQ)

[latest.log](https://github.com/ReplayMod/ReplayMod/files/6722458/latest.log)
[Crash-report.txt](https://github.com/ReplayMod/ReplayMod/files/6722460/Crash-report.txt)

Problematic replay: [Replay.zip](https://github.com/ReplayMod/ReplayMod/files/6722462/Replay.zip)

**Comment by Johni0702** [comment]
Hm, not entirely sure what the error means exactly but I noticed that the internal file name it is trying to access is 261 characters long (cause it encodes non-ascii characters as 4 ascii characters) and iirc there is a limit of 255 characters on file names in Windows.
Could you check if renaming the replay to something shorter fixes the issue? If so, I'll have to think of some way to abbreviate internal file names to prevent that from happening in the future.

**Comment by Felix14-v2** [comment]
Indeed, the problem was in the long file name.
By the way, why not just save the source text? ReplayMod detects such replays well.
![Снимок экрана 2021-06-28 091936](https://user-images.githubusercontent.com/75726196/123589773-60bd2c80-d7f2-11eb-80d8-fc7779322d74.jpg)

**Comment by Johni0702** [comment]
> By the way, why not just save the source text? ReplayMod works well with such replays.

Because certain characters (and sometimes even character combinations) are not allowed in file names. And which ones depends very much on the operating system and file system in use, with no reliable way to tell, so we cannot just blacklist those, instead we whitelist those which we know to definitely be OK (iirc a-z, A-Z, 0-9, _ and -). Though looking at how difficult this makes navigating the folder if you primarily use non-latin characters, I guess it's at least worth it to try the raw name before going the safe route. Opened #536 for that.

**Comment by Felix14-v2** [comment]
Huge thanks!
