### ISSUE TITLE
Bug with button Replay mod from FancyMenu mod on MC 1.17.1

### ISSUE THREAD

**Issue by Disguys** [ReplayMod/ReplayMod#577]
**Describe the bug**
Error displaying the Replay mod button from FancyMenu on MC 1.17.1
The developer of the FancyMenu mod say that it is necessary to inform you.

**To Reproduce**
1. Install Replay mod and FancyMenu on Fabric 1.17.1
2. Turn on the customization menu and make sure that the button associated with replay mod is gone.

! On MC 1.16.5 there was no such mistake. !

**Expected behavior**
Display the replay mod button with the customization menu

**Screenshots**
![](https://cdn.discordapp.com/attachments/589022386620203019/881942150919639171/unknown.png)
![](https://cdn.discordapp.com/attachments/589022386620203019/881942260432896020/unknown.png)

**Comment by Disguys** [comment]
https://github.com/Keksuccino/FancyMenu/issues/195

**Comment by Johni0702** [comment]
In the `.minecraft/config/replaymod.json` change the `mainMenuButton` to `BIG`.
![](https://i.johni0702.de/Tush8.png)

If that doesn't work, then FancyMenu needs to be more specific about what "the correct way" is supposed to be.

**Comment by Disguys** [comment]
The button is displayed with the value "default", but for some reason does not want to be displayed with other values, what can this be related to?

**Comment by Johni0702** [comment]
The icon-style buttons use a different way to inject themselves into the main menu (they basically just draw on top) because that's easier to manage across the 15 Minecraft versions we support.
The big button injects an actual button into the menu (and moves around the other buttons), hence why FancyMenu may be able to detect it.

Could you confirm that FancyMenu is fully functional with the big button? If so, I'll try to change the icon-style buttons to real ones with RM 2.7 as well.

**Comment by zeresss** [comment]
I am also expereincing this but button appears on layout editor.
![1](https://github.com/ReplayMod/ReplayMod/assets/118597972/d6b21fc0-f71f-448a-a371-f0fe91c9b92e)
