### ISSUE TITLE
Why dose "scrubbing" reload my world, EVERY TIME!!!

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayMod#594]
Why replay it do this, I just want to preview my original recording. 😞 

P.S: Also I mean scrubbing on the top bar.

P.P.S: also I seem to only happen to me. (I currently can't show you my specs and mods. but I can tell you I have the [Fabulously Optimized](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized) modpack installed, plus my computer is _REALLY SLOOW_

**Comment by RaderRMT** [comment]
maybe because the replaymod has to tell minecraft to play everything between where you are in time and where you want to go in time. going back is time takes longer because the replaymod has to tell minecraft to replay everything from the start up to where you want to jump in time.

and please use the discord for future questions

**Comment by ErrorBot1122** [comment]
but why does it only happen to me, not any other youtube...

**Comment by RaderRMT** [comment]
> and please use the discord for future questions

**Comment by ErrorBot1122** [comment]
:(

**Comment by Kepler-17c** [comment]
> Also I only posted it here because I thought it was a bug

Please use the Discord. It's easier to sort things out there. And if it really is a bug, we will ask you to post details here or create the issue for you.  
This issue tracker is just not made for support...

**Comment by ErrorBot1122** [comment]
i found out what the issue was, I just need to use quick mode!

Thanks to [Kepler-17c](https://github.com/Kepler-17c) for the help, again _x2_
