### ISSUE TITLE
Setting: Add interface for record

### ISSUE THREAD

**Issue by Timtaran** [ReplayMod/ReplayMod#609]
(Inventory, chests, tittles)

**Comment by Johni0702** [comment]
Probably not happening. As for why, here's a message I once wrote on Discord:
> regardless of whether "it's worth it", from my point of view this is more an issue with feasibility:
the only reason the ReplayMod as a concept is feasible, is because there already exist a generic way to serialize (i.e. convert to/from a consistent binary fromat) the entire world state in Minecraft because that's fundamentally required for multiplayer to work (and singleplayer is just running an integrated server these days). all the world state has to somehow be replicated over the network and we can just take that replication data and store it for later (in actuality there's lots of complicating factors but vastly simplified that's how it works).
> there's no such thing for GUIs. MC has no need to sync the exact state of one client's user interface to any other client. as such there's no generic way to record and later replay that state. and without a generic way to do that, it's basically a pick two out of three:
> - compact storage and flexible replay (i.e. not just a generic screen recorder)
> - possible to implement and maintain within reasonable effort
> - supports all the GUIs (including with third-party mods)
