### ISSUE TITLE
Missing Licensing for Assets including Branding

### ISSUE THREAD

**Issue by TheKodeToad** [ReplayMod/ReplayMod#615]
I have ported Replay Mod to another platform, and it involved changing quite a lot of the code to remove dependency on Forge API.
Porting alone may be different, but I actually fixed a few bugs (too hacky to get merged into Replay Mod, unfortunately), and even went as far as to change the recording indicator's icon, and allow it to be moved.
The code is available on GitHub under the same license (at least, all the code that is modified from Replay Mod, the rest of the code is MIT).

Replay Mod does not specify the license of the name and logo, and I do not want to violate it.

**Comment by Johni0702** [comment]
Licenses do not apply to the name / logo. A trademark would but we don't have one registered because that's not trivial to do and there's not really been any reason so far to do it.

As long as you make clear, whether from context or content, that your ReplayMod fork is merely based on but not the same as this one, you should be good. E.g. calling it "ReplayMod Sol Edition", adding a tiny version of your logo to the RM logo and making sure people know to get support from you if they cannot reproduce the issue with the original.

We'll let you know should this ever change.
