### ISSUE TITLE
Items in crafting table disappear when using ReplayMod with JEI

### ISSUE THREAD

**Issue by 2687e8** [ReplayMod/ReplayMod#62]
- ReplayMod version: 1.12.2-2.2.0-b4
- Forge version: 14.23.5.2838
- JEI version: 4.15.0.268 and 4.15.0.285 (I confirmed this issue at least these versions, didn't try in other versions)

Normally, pressing Esc or E key will close only recipe viewer screen of JEI, but with replaymod, it closes both of recipe viewer and crafting screen. This causes item disappearing issue when crafting items and viewing some recipes.

**Comment by Johni0702** [comment]
NEI or JEI (you mentioned both)?
Is there any difference when using RM 2.1.4?

**Comment by 2687e8** [comment]
I'm using only JEI. It didn't happen when I tried with RM 2.1.4, seems a beta-only issue. Thank you!

**Comment by Johni0702** [comment]
This should be fixed as of 2.2.0-b5.

This turned out to be two separate issues.
The E issue was fixed as a side effect of fixing the `Record Singleplayer/Multiplayer` checkboxes (https://github.com/ReplayMod/jGui/commit/7d66b9a92452a768fafc4db24755b620ffa41a51).
The Esc issue actually affected any GUI though I don't think it applies to any vanilla GUI since none of them do not fully close on Esc, i.e. all of them fully close on Esc anyway (https://github.com/ReplayMod/jGui/commit/1daefddfb8f0dc4aba179b9a725936d3e00aba49)
