### ISSUE TITLE
1.18.1 crashes when loading into a world

### ISSUE THREAD

**Issue by PixusPanic** [ReplayMod/ReplayMod#620]
I've just downloaded the 1.18.1 version of ReplayMod and whenever I try to load into a world, the game crashes, with the crash log saying it couldn't read " read field "field_3911" because "this.field_4015.field_1724" is null". I've read that [this was an issue in an earlier version of the mod](https://www.reddit.com/r/Minecraft/comments/ozg8oe/replay_crash/) and that someone else also said they were having issues with it. A fix would be greatly appreciated.

[crash-2021-12-12_01.43.07-client.txt](https://github.com/ReplayMod/ReplayMod/files/7698236/crash-2021-12-12_01.43.07-client.txt)

**Comment by Kepler-17c** [comment]
Please use the Discord server at https://discord.gg/5GR7RSb for support.

To me it look like you have the wrong version of Iris - use the one you get from the installer (instructions pinned in #support).

**Comment by Johni0702** [comment]
See above. Iris currently distributes two, non-identical 1.1.3 for 1.18.1 versions (although they're named identical!). The installer version was first, so that's what our Sodium is compatible with.
You're on 1.18.1, so you need to use the Sodium for 1.18.1 from https://replaymod.com/download/ together with the Iris for 1.18.1 from the Iris installer.
