### ISSUE TITLE
Game crashes if you click on different positions on the timeline too quickly, jukebox stops working when you enter the pause menu and old blocks that I have already broke still show in the replay

### ISSUE THREAD

**Issue by Cl3arL5gg** [ReplayMod/ReplayMod#687]
The title says it all, and here's a picture of the "block bug"
![replay mod bug](https://user-images.githubusercontent.com/79581780/155674257-cd4a8478-939f-4930-83a0-d9dce6ad8d24.png)

**Comment by Johni0702** [comment]
Please open one ticket per actionable issue.

For the crash, please include the crash report as well as the `latest.log` file from right after the crash (before restarting MC).

For the jukebox, please describe in more detail how you're expecting it to behave and how it actually behaves. The jokebox stopping when you enter the pause menu doesn't sound wrong it me given the game is paused at that point.

The "blocks" bug aren't actually blocks, those are the break particles. If you unpause the replay, they will quickly decay. Their presence may have multiple causes. Assuming you jumped to that part of the replay either from the beginning where the blocks still existed or backwards in time (which simply restarts the replay, i.e. also jumps from the beginning), then that's because the game isn't being fully simulated while jumping, cause that would make jumping way slower than it already is. There is https://github.com/ReplayMod/ReplayMod/issues/311 to eventually fix that for most short-lived animations.
