### ISSUE TITLE
Sample recording / rendering from player perspective not interpolated, not editable, not configurable. 

### ISSUE THREAD

**Issue by psycho-history** [ReplayMod/ReplayMod#702]
It is hopeless....

Here a sample of rendering with ReplayMod from player perspective. Stuttering recorded in gameplay gives rendering with NO quality at all. Because of that you can make the conclusion that the quality of ReplayMod itself, and its maintainers is very poor.
I'm not throwing with shit, i'm looking at it.

https://www.youtube.com/watch?v=zYzuqnoWKkg

It freezes!!! Just like in the gameplay.... OMG!!!

**Comment by psycho-history** [comment]
No go bully bashing. Live your eGO!

**Comment by psycho-history** [comment]
Only leave negative responses please.

**Comment by Kepler-17c** [comment]
There actually is interpolation - but with player perspective, head movement dominates.

When you make a real-time render, you can see the smooth motion.

Sped up it's obviously yanky, because ReplayMod doesn't drop position data.

For cinematic camera movement you have the free position-keyframes - like you demonstrated in your video.

**Comment by Kepler-17c** [comment]
And about freezes: What do you expect from jumpy position data? When your game freezes, timings get messed up.
