### ISSUE TITLE
bow animation and arrow not showing in 1st person view

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#708]
ReplayMod 1.18.2-2.6.4; no other mods

![image](https://user-images.githubusercontent.com/31929183/159303583-d448906f-7fd1-4b6c-bbb6-3967aed5650b.png)

In 3rd person you can see the bow animation and the arrow, in 1st person you can't.

[2022_03_21_17_12_03.zip](https://github.com/ReplayMod/ReplayMod/files/8317143/2022_03_21_17_12_03.zip)

**Comment by MaxedOut1** [comment]
Incase this helps atall the bug has been in all replay mod versions from 1.9 - 1.18.
On 1.8.9 this bug is not present.
I assume its something to do with the Combat update changing something. Good luck!

fyi: My minecraft server recently updated to 1.18.2 from 1.8.9, the players on my server are minecraft editors who create edits and montages. We all use replay mod. A couple of hundred people are waiting on this to be fixed so we can start using the new server to create bow edits and much more! Just know that lots of people appreciate your work and would love for this bug to be fixed as soon as possible!
Thanks,
MaxedOut

**Comment by MaxedOut1** [comment]
Hey! Just noticed this bug also happens when pulling back the crossbow! Your welcome!
