### ISSUE TITLE
When player accesses crafting table the inventory screen pops up (Benchmark 2 Fabric Pack)

### ISSUE THREAD

**Issue by Mondays3** [ReplayMod/ReplayMod#713]
So when I am making a camera move in replay mod, either first person or using camera, when the player opens the crafting table the inventory comes up and all the items move as they do in the replay.
![Auto crafting table open](https://user-images.githubusercontent.com/75327048/160264982-b415dedb-c088-496e-9079-71b5a9c32ceb.png)

As well as this I can access the inventory manually with "e" and I can move items in the inventory also.
This bug doesn't happen for any other inventory such as furnaces or chests, however I haven't tried any modded machines yet.

I am using the benchmark 2 pack version 0.6.12 which is using fabric 0.13.2.

Installed I am using 
replaymod-1.18.1-2.6.4.jar
sodium-fabric-mc1.18.1-0.4.0-alpha6+replaymod.rev.b90e7f3.jar

The pack comes with sodium-extra-mc1.18.1-0.3.9.jar if that does anything.
It also has iris-mc1.18.1-1.2.0-pre.jar.

I'm using the shader: Sildur's+Vibrant+Shaders+v1.32+Extreme but the bug happens with or without shaders enabled.

I've tried using older versions of sodium through the replay mod website as well as different sodium and iris versions from cureforge with replay mod. Either the game crashed/never loaded or the bug would still appeared.

I see that this was an issue before through the replay forums back in 1.14 but don't know if this is due to mod conflicts or something else?

**Comment by Johni0702** [comment]
This probably happens because some mod changes the way the crafting inventory screen is opened to use a custom packet instead of the vanilla open screen packet, so ReplayMod can't filter it out.

You would have to figure out which mod that is, and then we'd have to get that mod to switch to the vanilla open screen packet instead of its custom thing (and/or there might be another generic way for ReplayMod to suppress the screen).

Being able to open the inventory manually is a known "bug". That is, it's not meant to open but that code broke some time around 1.14 and being able to open it has turned out to be useful at times, so I'm hesitant to "fix" it.

**Comment by Rainstripes** [comment]
How do you find and filter modded elements in the code? I'm having this problem with Farmer's Delight pots and Sophisticated Backpacks too. I understand it won't be completely removed, but just finding what caused it and why isn't exactly a solution.
