### ISSUE TITLE
Using Shaders in a long recording crashes rendering

### ISSUE THREAD

**Issue by Herobrine2143** [ReplayMod/ReplayMod#739]
When I try to use shaders it crashes when is around near the beginning of the render, When trying to use the High Performance render it only gets as far as half-way through. It works fine if  is a short recording, with all the mods installed I have, but I even disabled all of the mods that I don't need and enabled the ones that Replay requested to have and still have the same problem.

I'm using **Minecraft 1.17.1 | Replay Mod 2.6.5 | Sodium 0.3.4+replaymod.rev.a951858 | Shaders - Complementary Shaders v4.3.1**

### Without the other mods:
[crash-2022-05-27_19.10.44-client.txt](https://github.com/ReplayMod/ReplayMod/files/8788810/crash-2022-05-27_19.10.44-client.txt)

Log: [latest.log](https://github.com/ReplayMod/ReplayMod/files/8788872/latest.log)

### With other mods:
[crash-2022-05-27_18.29.26-client.txt](https://github.com/ReplayMod/ReplayMod/files/8788900/crash-2022-05-27_18.29.26-client.txt)

Log: https://paste.ee/p/wlaPz

**Comment by Johni0702** [comment]
Looks like ffmpeg is dying midway through. Usually this is because you're running either out of disk space or out of memory.
ffmpeg's log is written to a file called `export.log` directly in the `.minecraft` folder. Please attach that file.

Also, your "without the other mods" log still has tons of other mods installed, so you might have gotten the wrong log there.
