### ISSUE TITLE
Crashes at the end of renders and disappearing chunks

### ISSUE THREAD

**Issue by jbrigljevic** [ReplayMod/ReplayMod#767]
I've been experiencing problems with the previews of the recordings. The issue is present only when changes had been made using the FAWE or FAVS mods, when the chunks that are being changed (or possibly just the selection, I am not sure) disappear for a second and then reappear afterwards. I've tried changing my mods combinations to figure out what is causing the problem and these are my observations:

1.  The issue persists when using _only_ the newest version of the ReplayMod (v2.6.8) **and** the newest sodium version that is compatible with the mod
2.  The issue is solved when that sodium version is disabled, meaning the chunks do not glitch out
3.  The issue is also nonexistant when using a normal sodium version (note: running the game using this setup and then going back to the setup with the replaymod compatible sodium version **does not** reproduce the issues, i.e. the preview does not have the glitches, and the render finished without a problem; a PC restart is what is then required to reproduce the problems)

As I've mentioned, during the rendering phase the visual glitches persist, and the game itself crashes at the end of the render, so I'm attaching the crash report as well as the latest log.
[crash-2022-08-22_13.10.47-client.txt](https://github.com/ReplayMod/ReplayMod/files/9393828/crash-2022-08-22_13.10.47-client.txt)
[latest.log](https://github.com/ReplayMod/ReplayMod/files/9393849/latest.log)

**Comment by Johni0702** [comment]
That's a bug in Sodium: https://github.com/CaffeineMC/sodium-fabric/issues/1016

The issue is timing dependent (something like when a chunk is loaded and immediately unloaded within the same frame), hence your strange observations.

Also, you're using RM and Sodium for 1.19 on 1.19.2, those are not compatible, I'm surprised this hasn't blown up in other ways.

> the newest sodium version that is compatible with the mod

All official versions as of Sodium 0.4.3 (the first version for 1.19.2) are compatible with RM. There are no inofficial versions for 1.19.2+.

> The issue is also nonexistant when using a normal sodium version 

RM-compatible Sodium behaves **exactly** identical to official Sodium except during and only during rendering. So the difference you're seeing here is not because of the difference between official and RM-compatible Sodium, it's the difference between two different versions of Sodium (and presumably different timings that result from that).
