### ISSUE TITLE
Where is entity positioning decoding for replays located?

### ISSUE THREAD

**Issue by JackBPrograms** [ReplayMod/ReplayMod#773]
Hey, This isn't really an issue, more of a question, but I'm wondering where the decoding for entity poisoning is inside the code. I have looked around a lot in `replaymod/src/main/java/com/replaymod/replay` but haven't found it. Thanks!

**Comment by Johni0702** [comment]
For regular playback it's done by Minecraft. That's how ReplayMod manages to be compatible with the vast majority of content mods: It's by design mostly oblivious to them. A replay just looks like a regular server for the most part.
For ReplayStudio features (QuickMode, Start/Stop/Pause/Resume, Edit, Spectator Keyframe preview, etc.; i.e. the stuff where RM itself needs to know what actually happens in the recording without playing it) position tracking happens [here](https://github.com/ReplayMod/ReplayStudio/blob/b2c999d4f9223ae67b3d0ac58fd36e9f331351b9/src/main/java/com/replaymod/replaystudio/util/PacketUtils.java#L76) and branches out depending on the packet.
