### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by crazybytes** [ReplayMod/ReplayMod#79]
First:
Your ReplayMod does not compile under Ubuntu.
Message this, message that. Nothing works.
So, how to compile?

Second:
Using the ReplayMod gives lots of errors when loading.
While everything should be ok.
Shadermod, Optifine, Mixin, use depends instead of requires,  skipping bad option, etc.

So, tell me the configuration/commands/versions for gradle, and the configuration for 1.12.2, 1.14.3 and/or 1.14.4 so things work.....
Tia.

**Comment by Johni0702** [comment]
> Your ReplayMod does not compile under Ubuntu.

It works fine on my machine (QubesOS/Fedora 29) and every commit is also built in a clean docker container based on the `maven` image (maven only for legacy reasons, by now just a jdk one should do).

 > Message this, message that. Nothing works.

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

> So, how to compile?

```
./gradlew :jGui:1.7.10:setupCIWorkspace :1.7.10:setupCIWorkspace
./gradlew --parallel
```
See https://github.com/ReplayMod/ReplayMod/blob/94d6e7cb4bbffb9bf2f2f86448fc1e3d15c8946b/.drone.yml

> Using the ReplayMod gives lots of errors when loading.

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

> Shadermod, Optifine, Mixin, use depends instead of requires, skipping bad option, etc.

Shadersmod is incompatible with Optifine and hasn't been supported by the ReplayMod since a few years ago (only in the 1.0.x releases).
Not sure what you mean by `use depends instead of requires` or `skipping bad option`, etc.

> So, tell me the configuration/commands/versions for gradle, and the configuration for 1.12.2, 1.14.3 and/or 1.14.4 so things work.....

The required gradle version is the one which has been configured for the included wrapper.
The configuration is quite complex since we're compiling for ~10 MC versions (including Forge and Fabric versions) from a single source directory. It's all included in the repo though. If you have specific questions, ask them.
