### ISSUE TITLE
the game crashes after clicking replay mod menu

### ISSUE THREAD

**Issue by ary4nk** [ReplayMod/ReplayMod#847]
the game crashes after clicking replay mod menu before crashing it says saving .
link to crash report : https://mclo.gs/XIMw8wW

**Comment by Johni0702** [comment]
Here's a snippet I wrote on this a while ago:

> this is a bug deeply rooted in the design of the current gui library which RM uses, and as such is quite difficult to fix (so I've more or less stopped trying, especially because I will slowly transition to a different gui lib anyway). this happens when a key is pressed on the very first frame after the Replay Viewer screen (or really any RM gui) is opened.
usually super easy to avoid but I recall there was one case years back where for some unknown reason someone's mouse (or keyboard?) driver would always send a keypress immediately after they clicked something, thereby reliably triggering this bug. unfortunately I have no way to find that conversation and I don't recall how they solved it but I'm guessing you've got the same issue. if you happen to own a different mouse or have some other way to click the button, then try playing around with that, or try re-plugging your mouse. I vaguely remember something like that helping them solve it.

And if changing the mouse doesn't help, it could also be a purely software thing like it was for this user:

> I used a software called "x-mouse button control"  to assign another key to the left click for the convenience of the keyboard. It seems that was the cause. I didn't think the mouse was it.


Closing the issue because as explained above I do not plan on fixing this specifically (it will eventually be fixed as a side effect of migrating away from the current gui lib).
