### ISSUE TITLE
Morph mod doesnt show when replayed

### ISSUE THREAD

**Issue by gapazopongapa** [ReplayMod/ReplayMod#87]
I know this is more an issue with incompatibility but I still find it kind of frustrating that the mobs that I morph into are not showing on the replays, which is the main reason why I installed this mod, but maybe is just my computer, does it normally work?

**Comment by Johni0702** [comment]
1. There are multiple morph mods (even more so because you didn't specify any MC version)
2. This needs to be fixed in the morph mod.
The RM works by recording client-bound packets and for any mod to work with it, that mod must echo back any client-side changes the server receives to all clients, including the one that triggered it or it must specifically hook into the RM (though the first approach is strongly preferred since the RM doesn't have any stable API).
Manually adding support for specific third-party mods to the RM will very quickly end with an insurmountable amount of maintenance work.
