### ISSUE TITLE
Any plans for 1.14.4 (Forge)?

### ISSUE THREAD

**Issue by SepSol** [ReplayMod/ReplayMod#90]

**Comment by Johni0702** [comment]
None.
- There's little gain (RM doesn't need any of Forge's features, on the contrary, parts of Forge make RM's job actually more difficult) for lots of work (especially in the long term, I'd like to avoid adding more versions, we're already somewhere around 12 different ones iirc).
- Mixin 0.8 has yet to be released (though it's getting there) and older versions no longer work with the newer forge.
- We lack active developers. It's been only me for the last few years and I've more or less stopped as well now (now as in three months ago). There are still tons of bugs in version 2.2.0-b7 but I lack the motivation (and by extension the time) to work on them (especially because I never use the mod myself and have found more fun things to mod).

**Comment by SepSol** [comment]
That's sad :(
Thank you for the explanation tho
