### ISSUE TITLE
Forge 1.20.1

### ISSUE THREAD

**Issue by lynrayy** [ReplayMod/ReplayMod#941]
Why it works on 1.20.1 neoForge but it's not declared on mod page?

**Comment by RaderRMT** [comment]
The ReplayMod is not designed to work on NeoForge

**Comment by lynrayy** [comment]
But it works (but cause crash on server disconnect). It. Just. Works!

**Comment by Johni0702** [comment]
It does not. Just because you haven't personally run into any of the various issues with it, doesn't mean it works for everyone all the time.

**Comment by lynrayy** [comment]
You need to support it on (neo)forge

**Comment by mvl666Darkrio** [comment]
They don't "need" to do anything. They're not going to support anything that isn't fabric.

**Comment by RaderRMT** [comment]
> The mod community is separated in 2 and you're doing nothing to reunite it.
There are people that embrace modern tools while others are stuck in the past
Just because one dev doesn't want to give Fabric a try means it sucks (spoiler: it does not)
Fabric has the friendliest community by far, both on the dev side and the user side, and I see no reason to make Forge mods anymore unless you're modding 7+ years old versions. It simply isn't worth it.

**Comment by seacat17** [comment]
> Fabric has the friendliest community by far, both on the dev side and the user side, and I see no reason to make Forge mods anymore unless you're modding 7+ years old versions. It simply isn't worth it.
TerraFirmaCraft 1.20.1. Total conversion mod that always have been a Forge mod and that remains a Forge mod that canges Minecraft almost completely.

"Simply isn't worth it"? Fine. I'm not gonna argue anymore, this is hopeless.
